server:
    port: 9090
spring:
    application:
       name: Niscrum
    datasource:
        url: jdbc:mariadb://localhost:3306/niscrum
        username: root
        password: 123456
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop